### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by sfilmak**
Fixed screenshots

### CODE REVIEW

**Comment by creativetrendsapps** [comment]
The screenshots are fine.

**Comment by sfilmak** [comment]
For some reason, I see screenshots perfectly from other browsers like Opera or Chrome (or in a FastHub app on my phone), but Safari doesn't want to load them (see screenshots - first from Safari and the second one from Opera). 

If you will change screenshots links like I did - everything works fine in Safari. 

Safari: https://habrastorage.org/webt/8l/-r/7o/8l-r7olciaso6sinnldrblgb91m.png
Opera: https://habrastorage.org/webt/lc/ke/wq/lckewqcvrlruxi5kcjsqfaya0-4.png

**Comment by creativetrendsapps** [comment]
Screenshots are from the Play Store which uses webm format. I'm not sure if Safari supports this format.

**Comment by creativetrendsapps** [comment]
Opera is now based on Chromium and Firefox supports the format natively. I'll just go ahead and support the pull request though.

**Comment by creativetrendsapps** [comment]
Opera is now based on Chromium and Firefox supports the format natively. I'll just go ahead and support the pull request though.

**Pull request merged**
